package system

import (
	"os"
	"path/filepath"
	"slices"
	"testing"
)

func TestParseResolvConf(t *testing.T) {
	content := `# Generated by NetworkManager
nameserver 8.8.8.8
nameserver 1.1.1.1
search example.com corp.internal
`
	path := filepath.Join(t.TempDir(), "resolv.conf")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}

	servers, search, err := parseResolvConf(path)
	if err != nil {
		t.Fatalf("parseResolvConf: %v", err)
	}

	wantServers := []string{"8.8.8.8", "1.1.1.1"}
	if !slices.Equal(servers, wantServers) {
		t.Errorf("servers = %v, want %v", servers, wantServers)
	}

	wantSearch := []string{"example.com", "corp.internal"}
	if !slices.Equal(search, wantSearch) {
		t.Errorf("search = %v, want %v", search, wantSearch)
	}
}

func TestParseResolvConf_CommentsAndBlanks(t *testing.T) {
	content := `
# comment line
; another comment

nameserver 10.0.0.1

search local
`
	path := filepath.Join(t.TempDir(), "resolv.conf")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}

	servers, search, err := parseResolvConf(path)
	if err != nil {
		t.Fatalf("parseResolvConf: %v", err)
	}

	if !slices.Equal(servers, []string{"10.0.0.1"}) {
		t.Errorf("servers = %v, want [10.0.0.1]", servers)
	}
	if !slices.Equal(search, []string{"local"}) {
		t.Errorf("search = %v, want [local]", search)
	}
}

func TestParseResolvConf_Empty(t *testing.T) {
	path := filepath.Join(t.TempDir(), "resolv.conf")
	if err := os.WriteFile(path, []byte(""), 0o644); err != nil {
		t.Fatal(err)
	}

	servers, search, err := parseResolvConf(path)
	if err != nil {
		t.Fatalf("parseResolvConf: %v", err)
	}
	if len(servers) != 0 {
		t.Errorf("servers = %v, want empty", servers)
	}
	if len(search) != 0 {
		t.Errorf("search = %v, want empty", search)
	}
}

func TestParseResolvConf_FileNotFound(t *testing.T) {
	_, _, err := parseResolvConf(filepath.Join(t.TempDir(), "nonexistent"))
	if err == nil {
		t.Error("expected error for missing file")
	}
}
