version: 2
project_name: aether-webd

builds:
  - main: ./cmd/aether-webd
    binary: aether-webd
    ldflags:
      - -X 'main.version={{.Version}}'
      - -X 'main.commitHash={{.ShortCommit}}'
      - -X 'main.branch={{.Branch}}'
      - -X 'main.buildDate={{.Date}}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: bengrewell
    name: aether-webui
  draft: false
  prerelease: auto
