package meta

import "context"

// VersionInfo holds build-time version metadata.
type VersionInfo struct {
	Version    string `json:"version" example:"1.2.0" doc:"Semantic version string"`
	BuildDate  string `json:"buildDate" example:"2026-02-18T12:00:00Z" doc:"Build timestamp"`
	Branch     string `json:"branch" example:"main" doc:"Git branch at build time"`
	CommitHash string `json:"commitHash" example:"a1b2c3d" doc:"Short git commit hash"`
}

// VersionOutput is the Huma response wrapper for VersionInfo.
type VersionOutput struct {
	Body VersionInfo
}

// BuildInfo holds Go toolchain and target platform details.
type BuildInfo struct {
	GoVersion string `json:"goVersion" example:"go1.25.0" doc:"Go toolchain version"`
	OS        string `json:"os" example:"linux" doc:"Target operating system"`
	Arch      string `json:"arch" example:"amd64" doc:"Target architecture"`
}

// BuildOutput is the Huma response wrapper for BuildInfo.
type BuildOutput struct {
	Body BuildInfo
}

// UserInfo holds the uid/name of the process owner.
type UserInfo struct {
	UID  string `json:"uid" example:"1000" doc:"Numeric user ID"`
	Name string `json:"name" example:"aether" doc:"Username"`
}

// GroupInfo holds the gid/name of the process primary group.
type GroupInfo struct {
	GID  string `json:"gid" example:"1000" doc:"Numeric group ID"`
	Name string `json:"name" example:"aether" doc:"Group name"`
}

// RuntimeInfo holds process-level runtime details.
type RuntimeInfo struct {
	PID        int       `json:"pid" example:"4821" doc:"Process ID"`
	User       UserInfo  `json:"user" doc:"Process owner"`
	Group      GroupInfo `json:"group" doc:"Process primary group"`
	BinaryPath string    `json:"binaryPath" example:"/usr/local/bin/aether-webd" doc:"Path to the running binary"`
	StartTime  string    `json:"startTime" example:"2026-02-18T12:00:00Z" doc:"Server start time (RFC 3339)"`
	Uptime     string    `json:"uptime" example:"2h30m0s" doc:"Time since server start"`
}

// RuntimeOutput is the Huma response wrapper for RuntimeInfo.
type RuntimeOutput struct {
	Body RuntimeInfo
}

// FrontendConfig describes how the frontend is being served.
type FrontendConfig struct {
	Enabled bool   `json:"enabled" example:"true" doc:"Whether frontend serving is enabled"`
	Source  string `json:"source" example:"embedded" doc:"Frontend source (embedded or directory)"`
	Dir     string `json:"dir" example:"" doc:"Custom frontend directory path, if any"`
}

// SecurityConfig holds security-related configuration.
type SecurityConfig struct {
	TLSEnabled       bool `json:"tlsEnabled" example:"false" doc:"Whether TLS is enabled"`
	TLSAutoGenerated bool `json:"tlsAutoGenerated" example:"false" doc:"Whether the TLS certificate was auto-generated"`
	MTLSEnabled      bool `json:"mtlsEnabled" example:"false" doc:"Whether mutual TLS is enabled"`
	TokenAuthEnabled bool `json:"tokenAuthEnabled" example:"true" doc:"Whether bearer token authentication is enabled"`
	RBACEnabled      bool `json:"rbacEnabled" example:"false" doc:"Whether RBAC is enabled"`
}

// StorageConfig holds persistent storage configuration.
type StorageConfig struct {
	DataDir string `json:"dataDir" example:"/var/lib/aether-webd" doc:"Directory for persistent state database"`
}

// MetricsConfig holds metrics collection configuration.
type MetricsConfig struct {
	Interval  string `json:"interval" example:"10s" doc:"Metrics collection interval"`
	Retention string `json:"retention" example:"24h" doc:"Metrics retention period"`
}

// AppConfig holds non-secret application configuration values for introspection.
type AppConfig struct {
	ListenAddress string         `json:"listenAddress" example:"127.0.0.1:8186" doc:"Server listen address"`
	DebugEnabled  bool           `json:"debugEnabled" example:"false" doc:"Whether debug mode is enabled"`
	Security      SecurityConfig `json:"security" doc:"Security configuration"`
	Frontend      FrontendConfig `json:"frontend" doc:"Frontend serving configuration"`
	Storage       StorageConfig  `json:"storage" doc:"Storage configuration"`
	Metrics       MetricsConfig  `json:"metrics" doc:"Metrics collection configuration"`
}

// ConfigInfo holds the active application configuration plus schema version.
type ConfigInfo struct {
	AppConfig
	SchemaVersion int `json:"schemaVersion" example:"2" doc:"Current database schema version"`
}

// ConfigOutput is the Huma response wrapper for ConfigInfo.
type ConfigOutput struct {
	Body ConfigInfo
}

// ProviderStatus describes a single registered provider's state.
type ProviderStatus struct {
	Name          string `json:"name" example:"system" doc:"Provider name"`
	Enabled       bool   `json:"enabled" example:"true" doc:"Whether the provider is enabled"`
	Running       bool   `json:"running" example:"true" doc:"Whether the provider is currently running"`
	EndpointCount int    `json:"endpointCount" example:"8" doc:"Number of registered endpoints"`
}

// ProvidersInfo holds the list of registered provider statuses.
type ProvidersInfo struct {
	Providers []ProviderStatus `json:"providers"`
}

// ProvidersOutput is the Huma response wrapper for ProvidersInfo.
type ProvidersOutput struct {
	Body ProvidersInfo
}

// DiagnosticCheck holds the result of a single store health diagnostic.
type DiagnosticCheck struct {
	Name    string `json:"name" example:"ping" doc:"Diagnostic check name"`
	Passed  bool   `json:"passed" example:"true" doc:"Whether the check passed"`
	Latency string `json:"latency" example:"1.2ms" doc:"Check execution time"`
	Error   string `json:"error,omitempty" doc:"Error message if the check failed"`
}

// StoreInfo holds store metadata and live diagnostic results.
type StoreInfo struct {
	Engine        string            `json:"engine" example:"sqlite" doc:"Storage engine type"`
	Path          string            `json:"path" example:"/var/lib/aether-webd/app.db" doc:"Database file path"`
	FileSizeBytes int64             `json:"fileSizeBytes" example:"524288" doc:"Database file size in bytes"`
	SchemaVersion int               `json:"schemaVersion" example:"2" doc:"Current schema migration version"`
	Status        string            `json:"status" example:"healthy" doc:"Overall store health (healthy, degraded, unhealthy)"`
	Diagnostics   []DiagnosticCheck `json:"diagnostics" doc:"Individual diagnostic check results"`
}

// StoreOutput is the Huma response wrapper for StoreInfo.
type StoreOutput struct {
	Body StoreInfo
}

// StoreInfoFunc returns live store metadata and diagnostics.
type StoreInfoFunc func(ctx context.Context) StoreInfo

// SchemaVersionFunc returns the current database schema version.
type SchemaVersionFunc func() (int, error)

// ProviderStatusFunc returns the status of all registered providers.
type ProviderStatusFunc func() []ProviderStatus
